language: java

jdk:

  - oraclejdk8  
  

  

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - wget -P "/home/travis/build/BrujosDeJava/jrpg-2017a-cliente/" https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
 - git clone https://github.com/BrujosDeJava/jrpg-2017a-dominio.git /home/travis/build/BrujosDeJava/jrpg-2017a-dominio